### ISSUE TITLE
Desafio curso js - ex011 - Condicionais em JavaScript

### ISSUE THREAD

**Issue by ernanidemiranda** [gustavoguanabara/javascript#33]
Senhores, alguém chegou a resolver o exercicio 011 que o Guanabara deixa como desafio no término da aula de Condições em JavaScript (Parte 2)?

Eu resolvi até uma parte, e logo me embasei no exercicio anterior que era semelhante, e não consegui fazer funcionar.

Peço ajuda de algum colega para encontrar o erro. 
Na hora da impressão ele sai como: 'A nacionalidade é *[object HTMLInputElement]*'

Certamente algum erro na sìntaxe, ou na passagem variavéis, parametros.

Segue o código:

![codigo_issue](https://user-images.githubusercontent.com/69490102/138132170-554896d1-1d60-4cf5-a856-0dd0b3a86c1b.jpg)

**Comment by santosvini** [comment]
Oi Ernani

no meu exercício, eu criei uma var de verificação(ver) = String(pais.value);
e essa var foi passada dentro da ${ver}.

Acredito que possa te ajudar.

Abs

**Comment by ernanidemiranda** [comment]
Vlwww Vini, era isso mesmo que estava faltando.. Depois ainda apanhei pq nao troquei a variavel na linha de baixo. mas agora deu tudo certo. agradeço o tempo tomado para ajudar.
