### ISSUE TITLE
Imagens não carregam 

### ISSUE THREAD

**Issue by ernanidemiranda** [gustavoguanabara/javascript#34]
Buenos galera, estou começando a estudar Js, e durante alguns exercícios me deparei com o seguinte caso.

O exercício é basicamente dois inputs, um pra captar a data e outro para validar através da função.

Eu já revisei conforme exercícios anteriores e não dou conta de achar o problema.

As imagens no diretório estão todas com os nomes idênticos, dentro da mesma pasta que os arquivos .js .html e .css
Já tentei alterar a forma de puxar a imagem dentro do if usando o setAtributtes, mas não tem jeito, ao inserir a data e clicar no "verificar" ele não carrega imagem nenhuma.

A única que carrega é a do .html, que eu deixei como uma imagem de capa/rosto/entrada, e ao inserir a data, carregaria outra imagem por cima.
Enfim se alguém puder dar um "bizu" no anexo, show de bola. Agradeço pela atenção de todos!

![duvidacondicionaljs](https://user-images.githubusercontent.com/69490102/138892142-f565de9b-abb9-4160-ba10-49552dc23a42.png)

**Comment by santosvini** [comment]
Bom Dia Ernani!

o seu segundo input tem um igual na frente dele, será que não é isso que esteja atrapalhando seu código no script?

**Comment by ernanidemiranda** [comment]
@santosvini bom dia, vou dar uma verificada. eu troquei o arquivo, pois tinha encontrado uns erros, porém, após ajustar, agora ele só carrega a imagem com nome irmao3.png

E sobre o os iguais ali, é so para dar um efeito, espaço entre os boxs na hora de aparecer na tela, mas ja tirei e testei e não era tambem ehhe

**Comment by santosvini** [comment]
@ernanidemiranda posta seu código aqui na issue, enquanto aparecer a imagem do irmão 3, quando vc digita o ano ele vai fazer a verificação dentro da condição, mas de toda forma, posta aqui e vamos analisar juntos

**Comment by ernanidemiranda** [comment]
function verificar(){

var ano = window.document.getElementById('txtano')
var img = window.document.getElementById('img')



if (ano== 1947 ) {
    
    img.src = ('mae.png') 

} else if (ano == 1950 ){

    img.src = ('pai.png')

} else if (ano == 1975){ 

    img.src = ('irmao1.png')

} else if (ano == 1980){
    img.src = ('irmao2.png')

} else if (ano == 1989 )  ;{
    
    img.src = ('irmao3.png')
}

}



Mesmo se eu digitar 1947 para entrar na primeira condição, ele já cai na ultima, e mostrando a imagem com o nome irmão3.png

**Comment by correantonio** [comment]
Bom dia meu querido, tudo bem?
Pode estar ocorrendo este problema por você estar armazenando o elemento HTML dentro da variável `ano`, e acredito que você queira guardar o valor digitado no seu input, certo?

Você está fazendo `var ano = window.document.getElementById('txtano')`
E para pegar o valor seria `var ano = window.document.getElementById('txtano').value`

Tente executar um `console.log()` no seu código, e depois execute um `console.log()` com a sugestão que lhe dei.

**Comment by correantonio** [comment]
> function verificar(){
> 
> var ano = window.document.getElementById('txtano') var img = window.document.getElementById('img')
> 
> if (ano== 1947 ) {
> 
> ```
> img.src = ('mae.png') 
> ```
> 
> } else if (ano == 1950 ){
> 
> ```
> img.src = ('pai.png')
> ```
> 
> } else if (ano == 1975){
> 
> ```
> img.src = ('irmao1.png')
> ```
> 
> } else if (ano == 1980){ img.src = ('irmao2.png')
> 
> } else if (ano == 1989 ) ;{
> 
> ```
> img.src = ('irmao3.png')
> ```
> 
> }
> 
> }
> 
> Mesmo se eu digitar 1947 para entrar na primeira condição, ele já cai na ultima, e mostrando a imagem com o nome irmão3.png

AAAAAA e mais uma coisa que acabei de perceber, geralmente estruturas de decisão if/else começam com o `if` e terminam com um valor padrão caso nenhum dos seus `else if` tenham dado certo, este valor padrão vc coloca dentro de um `else` que sempre fica por último. Sua estrutura está sem este ultimo parâmetro, e seu último `else if` está com um ; antes das chaves

**Comment by ernanidemiranda** [comment]
@antonioal97 buenos Antonio, tudo joia? obrigado por contribuir com a ajuda.
De fato coloquei o .value e nada mudou.. e mesmo com a estrutura daquela forma, ele teria que carregar ao menos  a primeira condição nao?

**Comment by ernanidemiranda** [comment]
@antonioal97 sobre o ; ao término, eu o coloquei pq o proprio vscode me segeriu, se não apresentava um erro. tbm nao entendi hehe.. vou te mostrar o print caso deixe sem o ;
