### ISSUE TITLE
Ola tudo bem, estou com problema, no exercios 4 da aula 06 , ele nao funciona,

### ISSUE THREAD

**Issue by Becero** [gustavoguanabara/javascript#43]
o comando que eu escrevi e:

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <script>
        var name = window.prompt("Qual e seu nome?") // Essa parte funcionou tranquilo
        document.write (`Seu nome tem ${nome.length}letras`) // Nao estou conseguindo execurtar, nao aparece nada na tela
    </script>
        
</body>
</html>

**Comment by Becero** [comment]
Ja entendi o que eu fiz, eu declarei a variavel com um nome e chamei ela depois com outro nome!

**Comment by santosvini** [comment]
Fecha sua issue man, como foi resolvido, melhor finalizar

**Comment by Becero** [comment]
Resolvi
