### ISSUE TITLE
aula 5 

### ISSUE THREAD

**Issue by alandelonbernardo** [gustavoguanabara/javascript#57]
var nome = "delon"
Uncaught ReferenceError: delon is not defined

Gostaria de entender por que quando eu tento fazer aparece essa mensagem de erro, e como corrigir ? Desde já agradeço.

**Comment by LeonardoSCN** [comment]
Está informando que Delon não foi definido, ideal é postar o código pra identificar o erro.

**Comment by alandelonbernardo** [comment]
Já consegui resolver, obrigado.

**Comment by BryanDamasioBRN** [comment]
Então com a Issue resolvida feche-a meu mano

**Comment by alandelonbernardo** [comment]
> var nome = "delon" Uncaught ReferenceError: delon is not defined
> 
> Gostaria de entender por que quando eu tento fazer aparece essa mensagem de erro, e como corrigir ? Desde já agradeço.
