### ISSUE TITLE
Problemas de reconhecimento da tag "innerText"

### ISSUE THREAD

**Issue by Diego0668** [gustavoguanabara/javascript#62]
Alguem sabe me dizer o porque a minha tag "innerText" não está achando? e se tem outra tag mais nova que serve a msm função 
![Captura de Tela (10)](https://user-images.githubusercontent.com/80727709/221992836-5cc6a9c1-afd3-42fa-a65e-f978dc874756.png)

**Comment by rafaelconstantinodev** [comment]
Achei uma anotação antiga de um exercício assim, porém não sei se é a solução que você quer.

var p1 = window.document.getElementByTagName('p')[1]
