### ISSUE TITLE
Exercício  JS (Parte 8) 

### ISSUE THREAD

**Issue by rebecaoliveira19** [gustavoguanabara/javascript#65]
Preciso de ajuda, quero saber qual parte do código esta errado, estou com dificuldade para entender o erro. 
Segue o código abaixo JavaScript:

let num = document.getElementById('fnum');
let tab = document.getElementById('sel');
let res = document.querySelector('div#res');
let valores = []

function inNumero(n){
    if(Number(n) >= 1 && Number(n) <=100){
        return true
    }else{
        return false
    }
}

function inList(n, l){
        if(l.indexOF(Number(n)) != -1){
            return true
        }else{
            return false
        }
}
function sum(){
    if(inNumero(num.value) && ! inList(num.value)){
        valores.push(Number(num.value))
        let item = document.createElement('option')
        item.text = `Valor ${num.value} adicionado`
        tab.appendChild(item)
        res.innerHTML  = ''

    }else{
        alert('valor inválido já encontrado na list')
    }
    num.value = ''
    num.focus()
}
function finalizar(){
    if(valores.length == 0){
        alert('Adicione valores antes de finalizar!')
    }else{
        let tot = valores.length
        let maior = valores[0]
        let menor = valores[0]
        for(let pos in valores){
                if(valores[pos] > maior){
                    maior = valores[pos]
                }if(valores[pos] < menor){
                    menor = valores[pos]
                }
            
        }
        res.innerHTML = ''
        res.innerHTML = `<p> Ao todo, temos ${tot} números cadastrados </p>`
        res.innerHTML += `<p> O maior valor informado  foi ${maior}.</p>`
        res.innerHTML += `<p> O menor valor informado foi ${menor}.</p>`
    }
}

**Comment by devpedromelo** [comment]
Olá, que tipo de erro está aparecendo ao executar o código? Pode ser um erro de sintaxe no **`indexOf`()**, se caso já resolveu, feche a issue!

**Comment by rebecaoliveira19** [comment]
Já consegui resolver
