### ISSUE TITLE
Ajuda no desafio 5

### ISSUE THREAD

**Issue by diogocarvalhoivo** [gustavoguanabara/javascript#73]
Ola pessoal.
Segue o trecho com problema do código:

### <body>
    <h1 id="tit">Conversor de medidas</h1>
    <input type="button" value="Converter" id="but" onclick="clicar()">
    <p>Clique no botão para inicar</p>
    <script>
        function clicar(){
            m=window.prompt('Digite uma distância em metros: ')
            Number(m)
            titulo = document.getElementById('tit')
            botao=document.getElementById('but')
            window.document.write(titulo.innerHTML+'<br>')
            window.document.write(`${m/1000} quilômetros (Km) <br>`)
            window.document.write(`${m/100} hectômetros (Hm)<br>`)
            window.document.write(`${m/10} decâmetros (Dam)<br>`)
            window.document.write(`${m*10} decímetros (dm)<br>`)
            window.document.write(`${m*100} centímetros (cm)<br>`)
            window.document.write(`${m*1000} milímetros (mm)<br>`)
        }
    </script>
</body>

O que acontece é que ao clicar no botão criado sou levado a outra página. Portanto, tive de escrever 'Conversor de medidas' novamente, para isso usei ###document.getElementById('tit') seguido de ###titulo.innerHTML. Contudo o texto perde a formatação da tag h1, já tentei o comando ###titulo.style.fontsize='2em', mas isso só altera o que está fora do script, ou seja, não consigo que após clicar no botão criado a formatação tanto do h1 id="tit">Conversor de medidas</h1 se mantenha.

Já para o botão é pior pois este some, e não sei como colocá-lo devolta.

![image](https://github.com/gustavoguanabara/javascript/assets/139460601/3398ce10-b5d1-48a2-ad85-eae8675cc1b1)
imagem quando aperto no botão

![image](https://github.com/gustavoguanabara/javascript/assets/139460601/d2fc7a8b-b9b0-4f0e-bacc-c84f3966763a)
imagem após submeter o valor da distância

**Comment by natan-xav2019** [comment]
Olha eu tentaria usar os métodos de escrita explicados em vídeo que e o ```innerHTML``` pois quando vc usa esse metodo ```.write``` vc re escreve todo o html

a estratégia que eu fiz foi por uma div com id="res" e dentro dela retornar a resposta

Nessa imagem vc ve a div com id="res"

![image](https://github.com/gustavoguanabara/javascript/assets/55638524/8dff514c-17e2-4336-bffe-d709e775b9de)

E usando o ```innerHTML``` depois de ter pego o id com um ```getElementById``` ou um ```querySelector```

![image](https://github.com/gustavoguanabara/javascript/assets/55638524/aeb0209d-53eb-474d-b149-46cc7d495a8b)

dessa forma a unica coisa alterada na pagina e a div id="res".

O link abaixo e da página em funcionamento caso queira conferir da minha solução.

[link do site](https://natan-xav2019.github.io/Curso-de-JavaScript/desafio/d005/)
