### ISSUE TITLE
Correção no desafio 12

### ISSUE THREAD

**Issue by SrCaioz** [gustavoguanabara/javascript#83]
No desafio 12 o resultado de valor antes = 1.000 e valor atual = 890 deveria ser de 11% e não 12,36%.Fórmula: ((1000 - 890) / 1000) * 100 = 11%. Código abaixo:

```javascript
let porcc = ((valAntes - valAtual) / valAntes) * 100
porcc = 11%
```

**Comment by webertrodrigues** [comment]
Eu consegui achar o valor citado no citado no desafio através de:
`var queda_porcentagem = ((preço_antigo/preço_atual)-1)*100`
Porem não faz sentido logicamente, pois tirando a prova real, resulta que o produto custava R$1.013 e alguns quebrados. Então usei a fórmula que dá 11% que na prova real dá certo:
`var queda_porcentagem = (1-(preço_atu/preço_ant))*100`
