### ISSUE TITLE
Uma dúvida na Aula 14 Repetições (parte2)

### ISSUE THREAD

**Issue by luizQF** [gustavoguanabara/javascript#97]
Olá, uma dúvida, estou iniciando agora mas tenho um pergunta, no while quando você colocou a condição c <= 6 o código executou 7 no total,  tipo:
var c = 1
while (c <=6){  //quando o c estiver valendo 6 ele vai adicionar mais um então vai ser 7
console.log(c) //vai sair 6 pois o 1 ainda n foi adicionado
c++
}
console.log(c)//vai sair 7 pois adicionou 1
então o valor final que vai sair vai ser 7
diferente do FOR q testa primeiro a condição e se for verdadeira adiciona um
 @gustavoguanabara

**Comment by JhonnatasRibeiroDev** [comment]
No seu exemplo com o while, a condição c <= 6 é testada antes de cada
execução do bloco de código. Ou seja, enquanto c for menor ou igual a 6, o
código dentro do while será executado.


Vamos detalhar o processo:

1. Inicialmente:

c começa com o valor 1 (var c = 1).

2. Execução do while:

Enquanto c <= 6, ele:

• Mostra o valor atual de c no console.log(c).

• Depois disso, incrementa c com c++ (adiciona 1 ao valor atual de c).

3. Quando o c chega a 6:

• Ele ainda atende à condição c <= 6.

• Mostra 6 no console.log.

• E incrementa c para 7.

4. Agora c = 7:

• A condição c <= 6 não é mais verdadeira, então o laço termina.

• Mas o c já foi incrementado, por isso, ao fazer console.log(c) fora do
while, o valor exibido é 7.


Diferença para o for


O for é um pouco diferente, porque:

• Ele testa a condição antes de executar o bloco, assim como o while.

• Mas o incremento acontece ao final de cada iteração, então o controle é
mais explícito no próprio cabeçalho do for.


Por exemplo:


for (var i = 1; i <= 6; i++) {

  console.log(i);

}

console.log(i);


Neste caso:

• O console.log(i) dentro do laço vai de 1 a 6, como esperado.

• Fora do laço, o i já foi incrementado uma última vez, então vale 7 (igual
ao comportamento do while).


Resumindo:

No while, o incremento acontece dentro do bloco manualmente. No for, ele
faz parte da estrutura, mas o resultado final é o mesmo se configurado de
forma parecida.


Em ter., 17 de dez. de 2024 às 11:06, Luiz Fernandes <
***@***.***> escreveu:

**Comment by luizQF** [comment]
Entendo, Obrigado pelo tempo...
